appraise_loss_task:
  description: >
    Analyze the theft crime scene and predict the missing values of stolen items using the RPT-1 model via the call_rpt1 tool. Use this dict {payload} as input.
  expected_output: >
    JSON with predicted values for the stolen items.
  agent: appraiser_agent

analyze_evidence_task:
  description: >
    Analyze the evidence of the theft that you can access via the grounding tool. 
    Provide any insights that can help in the investigation especially regarding alabies. 
    Check the evidence for all three suspect names 1. Sophie Dubois, 2. Marcus Chen and 
    3. Viktor Petrovand and provide an analysis for each of them.
  expected_output: >
    A detailed analysis of the evidence for each suspect, including any insights that can help in the investigation.
  agent: evidence_analyst_agent

solve_crime:
  description: >
    Find the thief from, the suspects by activating the evidence investigator agent and instructing him to look for the three suspects
    using the grounding tool. He should find information on alibies and motives and return a report for you to analyze. And use the appraise_loss_task from
    the appraiser agent to find the value of the stolen goods.
  expected_output: >
    The name of the thief and the total value of the stolen goods for the insurance.
  agent: lead_detective_agent